CREATE TABLE IF NOT EXISTS rooms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_number VARCHAR(32) NOT NULL UNIQUE,
  room_name VARCHAR(100) NOT NULL,
  room_type VARCHAR(30) NOT NULL DEFAULT 'washitsu',
  capacity INTEGER NOT NULL,
  base_price_per_person DECIMAL(10, 2) NOT NULL,
  private_bath BOOLEAN NOT NULL DEFAULT FALSE,
  occupancy_status VARCHAR(30) NOT NULL DEFAULT 'vacant',
  cleaning_status VARCHAR(30) NOT NULL DEFAULT 'cleaned',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  note VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_rooms_capacity_positive CHECK (capacity > 0),
  CONSTRAINT ck_rooms_base_price_non_negative CHECK (base_price_per_person >= 0)
);

CREATE TABLE IF NOT EXISTS room_price_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id INTEGER NOT NULL,
  rule_name VARCHAR(100) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  price_per_person DECIMAL(10, 2) NOT NULL,
  priority INTEGER NOT NULL DEFAULT 10,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  note VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_room_price_rules_date_range CHECK (start_date <= end_date),
  CONSTRAINT ck_room_price_rules_price_non_negative CHECK (price_per_person >= 0),
  CONSTRAINT uq_room_price_rules_seed UNIQUE (room_id, rule_name, start_date, end_date),
  CONSTRAINT fk_room_price_rules_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_room_price_rules_lookup ON room_price_rules (room_id, active, start_date, end_date, priority);

CREATE TABLE IF NOT EXISTS reservations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_no VARCHAR(16) NOT NULL UNIQUE,
  room_id INTEGER NOT NULL,
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  guest_name VARCHAR(100) NOT NULL,
  guest_kana VARCHAR(100),
  guest_phone VARCHAR(50),
  guest_email VARCHAR(255),
  guest_count INTEGER NOT NULL,
  payment_status VARCHAR(30) NOT NULL DEFAULT 'unpaid',
  reservation_status VARCHAR(30) NOT NULL DEFAULT 'booked',
  total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  note VARCHAR(500),
  cancellation_reason VARCHAR(1000),
  cancelled_by VARCHAR(64),
  cancelled_at TIMESTAMP WITH TIME ZONE,
  guest_gender VARCHAR(20),
  guest_age INTEGER,
  guest_category VARCHAR(10),
  reservation_form VARCHAR(50),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_reservations_stay_range CHECK (check_in_date < check_out_date),
  CONSTRAINT ck_reservations_guest_count_positive CHECK (guest_count > 0),
  CONSTRAINT ck_reservations_total_amount_non_negative CHECK (total_amount >= 0),
  CONSTRAINT ck_reservations_reservation_no_compact_sequence CHECK (REGEXP_LIKE(reservation_no, '^R[0-9]{6,}$')),
  CONSTRAINT fk_reservations_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT
);

CREATE SEQUENCE IF NOT EXISTS reservation_no_seq
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;

CREATE INDEX IF NOT EXISTS ix_reservations_room_status_dates ON reservations (room_id, reservation_status, check_in_date, check_out_date);
CREATE INDEX IF NOT EXISTS ix_reservations_status_checkin_id ON reservations (reservation_status, check_in_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_reservations_status_updated_id ON reservations (reservation_status, updated_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS room_inventory_blocks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id INTEGER NOT NULL,
  block_type VARCHAR(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason VARCHAR(1000) NOT NULL,
  record_status VARCHAR(20) NOT NULL DEFAULT 'effective',
  split_from_id INTEGER,
  version BIGINT NOT NULL DEFAULT 0,
  created_by VARCHAR(64) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cancelled_by VARCHAR(64),
  cancelled_at TIMESTAMP WITH TIME ZONE,
  cancellation_note VARCHAR(1000),
  CONSTRAINT fk_inventory_block_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT,
  CONSTRAINT fk_inventory_block_split FOREIGN KEY (split_from_id) REFERENCES room_inventory_blocks(id) ON DELETE RESTRICT,
  CONSTRAINT ck_inventory_block_range CHECK (start_date < end_date),
  CONSTRAINT ck_inventory_block_type CHECK (block_type IN ('stop_sale', 'maintenance')),
  CONSTRAINT ck_inventory_block_status CHECK (record_status IN ('effective', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS ix_inventory_block_lookup
  ON room_inventory_blocks(room_id, record_status, start_date, end_date);

CREATE TABLE IF NOT EXISTS room_inventory_block_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id VARCHAR(36) NOT NULL,
  block_id INTEGER NOT NULL,
  room_id INTEGER NOT NULL,
  event_type VARCHAR(30) NOT NULL,
  before_type VARCHAR(20),
  before_start_date DATE,
  before_end_date DATE,
  before_reason VARCHAR(1000),
  before_status VARCHAR(20),
  after_type VARCHAR(20),
  after_start_date DATE,
  after_end_date DATE,
  after_reason VARCHAR(1000),
  after_status VARCHAR(20),
  action_note VARCHAR(1000),
  actor_username VARCHAR(64) NOT NULL,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inventory_event_block FOREIGN KEY (block_id) REFERENCES room_inventory_blocks(id) ON DELETE RESTRICT,
  CONSTRAINT fk_inventory_event_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_rooms_active_updated_room_number ON rooms (active, updated_at DESC, room_number);

CREATE TABLE IF NOT EXISTS reservation_guests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id INTEGER NOT NULL,
  guest_name VARCHAR(100) NOT NULL,
  guest_kana VARCHAR(100),
  guest_gender VARCHAR(20),
  guest_age INTEGER,
  guest_category VARCHAR(10),
  guest_phone VARCHAR(50),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reservation_guests_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE
);

CREATE VIEW checkout_reservations AS
SELECT id, reservation_no, room_id, check_in_date, check_out_date, guest_name, guest_kana, guest_gender, guest_age, guest_phone, guest_email, guest_count, reservation_form, payment_status, reservation_status, total_amount, note, created_at, updated_at
FROM reservations
WHERE reservation_status = 'checked_out';

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_no VARCHAR(16) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(50),
  email VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS customer_no_seq START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE IF NOT EXISTS public_booking_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_no VARCHAR(18) NOT NULL UNIQUE,
  locale VARCHAR(5) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  lead_name VARCHAR(100) NOT NULL,
  lead_email VARCHAR(255) NOT NULL,
  lead_phone VARCHAR(50) NOT NULL,
  country VARCHAR(100) NOT NULL,
  guest_count INTEGER NOT NULL,
  total_amount DECIMAL(12, 2) NOT NULL,
  notes VARCHAR(1000),
  cancel_token_hash CHAR(64) NOT NULL UNIQUE,
  hold_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  confirmed_at TIMESTAMP WITH TIME ZONE,
  rejected_at TIMESTAMP WITH TIME ZONE,
  cancelled_at TIMESTAMP WITH TIME ZONE,
  rejection_reason VARCHAR(1000),
  cancellation_reason VARCHAR(1000),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_public_booking_cancellation_reason CHECK (
    status != 'cancelled' OR NULLIF(TRIM(cancellation_reason), '') IS NOT NULL
  )
);

CREATE SEQUENCE IF NOT EXISTS public_booking_request_no_seq START WITH 1 INCREMENT BY 1 MINVALUE 1;

ALTER TABLE reservations ADD COLUMN IF NOT EXISTS customer_id INTEGER;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS booking_request_id INTEGER;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS checked_in_at TIMESTAMP;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS checked_out_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS reservation_finances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id INTEGER NOT NULL UNIQUE,
  received_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(30),
  received_at TIMESTAMP,
  refund_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  refunded_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_finance_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE,
  CONSTRAINT ck_finance_refund_not_over_received CHECK (refund_amount <= received_amount)
);

CREATE TABLE IF NOT EXISTS admin_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMP,
  last_login_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backup_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  backup_file VARCHAR(1000) NOT NULL,
  status VARCHAR(20) NOT NULL,
  file_size_bytes BIGINT,
  message VARCHAR(1000),
  started_at TIMESTAMP NOT NULL,
  completed_at TIMESTAMP
);

-- V2 で予約列が増えた後の本番 view と同じ形に揃える。
DROP VIEW IF EXISTS checkout_reservations;
CREATE VIEW checkout_reservations AS
SELECT id, reservation_no, room_id, customer_id, check_in_date, check_out_date,
       checked_in_at, checked_out_at, guest_name, guest_kana, guest_gender,
       guest_age, guest_phone, guest_email, guest_count, reservation_form,
       payment_status, reservation_status, total_amount, note, created_at, updated_at
FROM reservations
WHERE reservation_status = 'checked_out';
