CREATE TABLE IF NOT EXISTS rooms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_number VARCHAR(32) NOT NULL UNIQUE,
  room_name VARCHAR(100) NOT NULL,
  room_type VARCHAR(30) NOT NULL DEFAULT 'washitsu',
  capacity INTEGER NOT NULL,
  base_price_per_person DECIMAL(10, 2) NOT NULL,
  private_bath BOOLEAN NOT NULL DEFAULT FALSE,
  occupancy_status VARCHAR(30) NOT NULL DEFAULT 'vacant',
  cleaning_status VARCHAR(30) NOT NULL DEFAULT 'cleaned',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  note VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_rooms_capacity_positive CHECK (capacity > 0),
  CONSTRAINT ck_rooms_base_price_non_negative CHECK (base_price_per_person >= 0)
);

CREATE TABLE IF NOT EXISTS room_price_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id INTEGER NOT NULL,
  rule_name VARCHAR(100) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  price_per_person DECIMAL(10, 2) NOT NULL,
  priority INTEGER NOT NULL DEFAULT 10,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  note VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_room_price_rules_date_range CHECK (start_date <= end_date),
  CONSTRAINT ck_room_price_rules_price_non_negative CHECK (price_per_person >= 0),
  CONSTRAINT uq_room_price_rules_seed UNIQUE (room_id, rule_name, start_date, end_date),
  CONSTRAINT fk_room_price_rules_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_room_price_rules_lookup ON room_price_rules (room_id, active, start_date, end_date, priority);

CREATE TABLE IF NOT EXISTS reservations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_no VARCHAR(16) NOT NULL UNIQUE,
  room_id INTEGER NOT NULL,
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  guest_name VARCHAR(100) NOT NULL,
  guest_kana VARCHAR(100),
  guest_phone VARCHAR(50),
  guest_email VARCHAR(255),
  guest_count INTEGER NOT NULL,
  payment_status VARCHAR(30) NOT NULL DEFAULT 'unpaid',
  reservation_status VARCHAR(30) NOT NULL DEFAULT 'booked',
  total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  note VARCHAR(500),
  guest_gender VARCHAR(20),
  guest_age INTEGER,
  reservation_form VARCHAR(50),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_reservations_stay_range CHECK (check_in_date < check_out_date),
  CONSTRAINT ck_reservations_guest_count_positive CHECK (guest_count > 0),
  CONSTRAINT ck_reservations_total_amount_non_negative CHECK (total_amount >= 0),
  CONSTRAINT ck_reservations_reservation_no_compact_sequence CHECK (REGEXP_LIKE(reservation_no, '^R[0-9]{6,}$')),
  CONSTRAINT fk_reservations_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT
);

CREATE SEQUENCE IF NOT EXISTS reservation_no_seq
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;

CREATE INDEX IF NOT EXISTS ix_reservations_room_status_dates ON reservations (room_id, reservation_status, check_in_date, check_out_date);
CREATE INDEX IF NOT EXISTS ix_reservations_status_checkin_id ON reservations (reservation_status, check_in_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_reservations_status_updated_id ON reservations (reservation_status, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS ix_rooms_active_updated_room_number ON rooms (active, updated_at DESC, room_number);

CREATE TABLE IF NOT EXISTS reservation_guests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id INTEGER NOT NULL,
  guest_name VARCHAR(100) NOT NULL,
  guest_kana VARCHAR(100),
  guest_gender VARCHAR(20),
  guest_age INTEGER,
  guest_phone VARCHAR(50),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reservation_guests_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE
);

CREATE VIEW checkout_reservations AS
SELECT id, reservation_no, room_id, check_in_date, check_out_date, guest_name, guest_kana, guest_gender, guest_age, guest_phone, guest_email, guest_count, reservation_form, payment_status, reservation_status, total_amount, note, created_at, updated_at
FROM reservations
WHERE reservation_status = 'checked_out';
