CREATE TABLE IF NOT EXISTS rooms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_number varchar(32) NOT NULL UNIQUE,
  room_name varchar(100) NOT NULL,
  room_type varchar(30) NOT NULL DEFAULT 'washitsu',
  capacity integer NOT NULL,
  base_price_per_person numeric(10, 2) NOT NULL,
  private_bath boolean NOT NULL DEFAULT false,
  occupancy_status varchar(30) NOT NULL DEFAULT 'vacant',
  cleaning_status varchar(30) NOT NULL DEFAULT 'cleaned',
  active boolean NOT NULL DEFAULT true,
  note varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_rooms_capacity_positive CHECK (capacity > 0),
  CONSTRAINT ck_rooms_base_price_non_negative CHECK (base_price_per_person >= 0)
);

CREATE INDEX IF NOT EXISTS ix_rooms_room_number ON rooms (room_number);
CREATE INDEX IF NOT EXISTS ix_rooms_active ON rooms (active);

CREATE TABLE IF NOT EXISTS room_price_rules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  rule_name varchar(100) NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  price_per_person numeric(10, 2) NOT NULL,
  priority integer NOT NULL DEFAULT 10,
  active boolean NOT NULL DEFAULT true,
  note varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_room_price_rules_date_range CHECK (start_date <= end_date),
  CONSTRAINT ck_room_price_rules_price_non_negative CHECK (price_per_person >= 0),
  CONSTRAINT uq_room_price_rules_seed UNIQUE (room_id, rule_name, start_date, end_date)
);

CREATE INDEX IF NOT EXISTS ix_room_price_rules_room_id ON room_price_rules (room_id);
CREATE INDEX IF NOT EXISTS ix_room_price_rules_dates ON room_price_rules (start_date, end_date);

CREATE TABLE IF NOT EXISTS reservations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_no varchar(30) NOT NULL UNIQUE,
  room_id integer NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
  check_in_date date NOT NULL,
  check_out_date date NOT NULL,
  guest_name varchar(100) NOT NULL,
  guest_kana varchar(100),
  guest_phone varchar(50),
  guest_email varchar(255),
  guest_count integer NOT NULL,
  payment_status varchar(30) NOT NULL DEFAULT 'unpaid',
  reservation_status varchar(30) NOT NULL DEFAULT 'booked',
  total_amount numeric(10, 2) NOT NULL DEFAULT 0,
  note varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_reservations_stay_range CHECK (check_in_date < check_out_date),
  CONSTRAINT ck_reservations_guest_count_positive CHECK (guest_count > 0),
  CONSTRAINT ck_reservations_total_amount_non_negative CHECK (total_amount >= 0)
);

CREATE INDEX IF NOT EXISTS ix_reservations_room_id ON reservations (room_id);
CREATE INDEX IF NOT EXISTS ix_reservations_check_in_date ON reservations (check_in_date);
CREATE INDEX IF NOT EXISTS ix_reservations_check_out_date ON reservations (check_out_date);
CREATE INDEX IF NOT EXISTS ix_reservations_status ON reservations (reservation_status);

ALTER TABLE reservations ADD COLUMN IF NOT EXISTS guest_gender varchar(20);
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS guest_age integer;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS reservation_form varchar(50);
ALTER TABLE reservations DROP COLUMN IF EXISTS channel;

CREATE TABLE IF NOT EXISTS reservation_guests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id integer NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
  guest_name varchar(100) NOT NULL,
  guest_kana varchar(100),
  guest_gender varchar(20),
  guest_age integer,
  guest_phone varchar(50),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE reservation_guests ADD COLUMN IF NOT EXISTS guest_gender varchar(20);
ALTER TABLE reservation_guests ADD COLUMN IF NOT EXISTS guest_age integer;

CREATE INDEX IF NOT EXISTS ix_reservation_guests_reservation_id ON reservation_guests (reservation_id);

CREATE OR REPLACE VIEW checkout_reservations AS
SELECT id, reservation_no, room_id, check_in_date, check_out_date, guest_name, guest_kana, guest_gender, guest_age, guest_phone, guest_email, guest_count, reservation_form, payment_status, reservation_status, total_amount, note, created_at, updated_at
FROM reservations
WHERE reservation_status = 'checked_out';
