CREATE TABLE IF NOT EXISTS rooms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_number varchar(32) NOT NULL UNIQUE,
  room_name varchar(100) NOT NULL,
  room_type varchar(30) NOT NULL DEFAULT 'washitsu',
  capacity integer NOT NULL,
  base_price_per_person numeric(10, 2) NOT NULL,
  private_bath boolean NOT NULL DEFAULT false,
  occupancy_status varchar(30) NOT NULL DEFAULT 'vacant',
  cleaning_status varchar(30) NOT NULL DEFAULT 'cleaned',
  active boolean NOT NULL DEFAULT true,
  note varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_rooms_capacity_positive CHECK (capacity > 0),
  CONSTRAINT ck_rooms_base_price_non_negative CHECK (base_price_per_person >= 0),
  CONSTRAINT ck_rooms_room_type CHECK (room_type IN ('washitsu', 'yoshitsu', 'suite', 'family')),
  CONSTRAINT ck_rooms_occupancy_status CHECK (occupancy_status IN ('vacant', 'reserved', 'occupied')),
  CONSTRAINT ck_rooms_cleaning_status CHECK (cleaning_status IN ('cleaned', 'needs_cleaning'))
);

CREATE INDEX IF NOT EXISTS ix_rooms_room_number ON rooms (room_number);
CREATE INDEX IF NOT EXISTS ix_rooms_active ON rooms (active);
CREATE INDEX IF NOT EXISTS ix_rooms_active_updated_room_number ON rooms (active, updated_at DESC, room_number);

CREATE TABLE IF NOT EXISTS room_price_rules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  rule_name varchar(100) NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  price_per_person numeric(10, 2) NOT NULL,
  priority integer NOT NULL DEFAULT 10,
  active boolean NOT NULL DEFAULT true,
  note varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_room_price_rules_date_range CHECK (start_date <= end_date),
  CONSTRAINT ck_room_price_rules_price_non_negative CHECK (price_per_person >= 0),
  CONSTRAINT uq_room_price_rules_seed UNIQUE (room_id, rule_name, start_date, end_date)
);

CREATE INDEX IF NOT EXISTS ix_room_price_rules_room_id ON room_price_rules (room_id);
CREATE INDEX IF NOT EXISTS ix_room_price_rules_dates ON room_price_rules (start_date, end_date);
CREATE INDEX IF NOT EXISTS ix_room_price_rules_lookup ON room_price_rules (room_id, active, start_date, end_date, priority);

CREATE TABLE IF NOT EXISTS reservations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_no varchar(16) NOT NULL,
  room_id integer NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
  check_in_date date NOT NULL,
  check_out_date date NOT NULL,
  guest_name varchar(100) NOT NULL,
  guest_kana varchar(100),
  guest_phone varchar(50),
  guest_email varchar(255),
  guest_count integer NOT NULL,
  payment_status varchar(30) NOT NULL DEFAULT 'unpaid',
  reservation_status varchar(30) NOT NULL DEFAULT 'booked',
  total_amount numeric(10, 2) NOT NULL DEFAULT 0,
  note varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_reservations_stay_range CHECK (check_in_date < check_out_date),
  CONSTRAINT ck_reservations_guest_count_positive CHECK (guest_count > 0),
  CONSTRAINT ck_reservations_total_amount_non_negative CHECK (total_amount >= 0),
  CONSTRAINT ck_reservations_payment_status CHECK (payment_status IN ('unpaid', 'paid')),
  CONSTRAINT ck_reservations_reservation_status CHECK (reservation_status IN ('booked', 'checked_out', 'cancelled'))
);

DROP VIEW IF EXISTS checkout_reservations;

ALTER TABLE reservations DROP CONSTRAINT IF EXISTS reservations_reservation_no_key;
ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ck_reservations_reservation_no_compact_sequence;
ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ck_reservations_reservation_no_10_digits;
ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ck_reservations_reservation_no_5_digits;

UPDATE reservations
SET reservation_no = 'R' || LPAD(id::text, 6, '0')
WHERE reservation_no !~ '^R[0-9]{6,}$';

ALTER TABLE reservations ALTER COLUMN reservation_no TYPE varchar(16);

ALTER TABLE reservations
  ADD CONSTRAINT ck_reservations_reservation_no_compact_sequence
  CHECK (reservation_no ~ '^R[0-9]{6,}$');

ALTER TABLE reservations
  ADD CONSTRAINT reservations_reservation_no_key UNIQUE (reservation_no);

ALTER TABLE rooms DROP CONSTRAINT IF EXISTS ck_rooms_room_type;
ALTER TABLE rooms DROP CONSTRAINT IF EXISTS ck_rooms_occupancy_status;
ALTER TABLE rooms DROP CONSTRAINT IF EXISTS ck_rooms_cleaning_status;
ALTER TABLE rooms
  ADD CONSTRAINT ck_rooms_room_type CHECK (room_type IN ('washitsu', 'yoshitsu', 'suite', 'family'));
ALTER TABLE rooms
  ADD CONSTRAINT ck_rooms_occupancy_status CHECK (occupancy_status IN ('vacant', 'reserved', 'occupied'));
ALTER TABLE rooms
  ADD CONSTRAINT ck_rooms_cleaning_status CHECK (cleaning_status IN ('cleaned', 'needs_cleaning'));

ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ck_reservations_payment_status;
ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ck_reservations_reservation_status;
ALTER TABLE reservations
  ADD CONSTRAINT ck_reservations_payment_status CHECK (payment_status IN ('unpaid', 'paid'));
ALTER TABLE reservations
  ADD CONSTRAINT ck_reservations_reservation_status CHECK (reservation_status IN ('booked', 'checked_out', 'cancelled'));

DROP SEQUENCE IF EXISTS reservation_no_seq;

CREATE SEQUENCE reservation_no_seq
  AS bigint
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;

SELECT setval(
  'reservation_no_seq',
  GREATEST(
    1,
    (SELECT COALESCE(MAX(CAST(SUBSTRING(reservation_no FROM 2) AS bigint)), 0) FROM reservations)
  ),
  (SELECT COUNT(*) > 0 FROM reservations)
);

CREATE INDEX IF NOT EXISTS ix_reservations_room_id ON reservations (room_id);
CREATE INDEX IF NOT EXISTS ix_reservations_check_in_date ON reservations (check_in_date);
CREATE INDEX IF NOT EXISTS ix_reservations_check_out_date ON reservations (check_out_date);
CREATE INDEX IF NOT EXISTS ix_reservations_status ON reservations (reservation_status);
CREATE INDEX IF NOT EXISTS ix_reservations_room_status_dates ON reservations (room_id, reservation_status, check_in_date, check_out_date);
CREATE INDEX IF NOT EXISTS ix_reservations_status_checkin_id ON reservations (reservation_status, check_in_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_reservations_status_updated_id ON reservations (reservation_status, updated_at DESC, id DESC);

CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ex_reservations_no_booked_overlap;
ALTER TABLE reservations
  ADD CONSTRAINT ex_reservations_no_booked_overlap
  EXCLUDE USING gist (
    room_id WITH =,
    daterange(check_in_date, check_out_date, '[)') WITH &&
  )
  WHERE (reservation_status = 'booked');

ALTER TABLE reservations ADD COLUMN IF NOT EXISTS guest_gender varchar(20);
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS guest_age integer;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS reservation_form varchar(50);
ALTER TABLE reservations DROP COLUMN IF EXISTS channel;

CREATE TABLE IF NOT EXISTS reservation_guests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id integer NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
  guest_name varchar(100) NOT NULL,
  guest_kana varchar(100),
  guest_gender varchar(20),
  guest_age integer,
  guest_phone varchar(50),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE reservation_guests ADD COLUMN IF NOT EXISTS guest_gender varchar(20);
ALTER TABLE reservation_guests ADD COLUMN IF NOT EXISTS guest_age integer;

CREATE INDEX IF NOT EXISTS ix_reservation_guests_reservation_id ON reservation_guests (reservation_id);

CREATE OR REPLACE VIEW checkout_reservations AS
SELECT id, reservation_no, room_id, check_in_date, check_out_date, guest_name, guest_kana, guest_gender, guest_age, guest_phone, guest_email, guest_count, reservation_form, payment_status, reservation_status, total_amount, note, created_at, updated_at
FROM reservations
WHERE reservation_status = 'checked_out';
