-- Add the local single-admin, customer history, stay lifecycle and finance model.
-- Existing reservation columns remain intact so the migration is non-destructive.

CREATE TABLE customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_no varchar(16) NOT NULL UNIQUE,
  name varchar(100) NOT NULL,
  phone varchar(50),
  email varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE SEQUENCE customer_no_seq AS bigint MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- Exact name/contact matches are grouped; different contact details never merge automatically.
INSERT INTO customers (customer_no, name, phone, email)
SELECT
  'C' || LPAD(nextval('customer_no_seq')::text, 6, '0'),
  guest_name,
  NULLIF(BTRIM(guest_phone), ''),
  NULLIF(LOWER(BTRIM(guest_email)), '')
FROM reservations
GROUP BY guest_name, NULLIF(BTRIM(guest_phone), ''), NULLIF(LOWER(BTRIM(guest_email)), '');

ALTER TABLE reservations ADD COLUMN customer_id integer REFERENCES customers(id) ON DELETE RESTRICT;
ALTER TABLE reservations ADD COLUMN checked_in_at timestamptz;
ALTER TABLE reservations ADD COLUMN checked_out_at timestamptz;

UPDATE reservations r
SET customer_id = c.id
FROM customers c
WHERE c.name = r.guest_name
  AND c.phone IS NOT DISTINCT FROM NULLIF(BTRIM(r.guest_phone), '')
  AND c.email IS NOT DISTINCT FROM NULLIF(LOWER(BTRIM(r.guest_email)), '');

CREATE INDEX ix_reservations_customer_id ON reservations(customer_id, check_in_date DESC);
CREATE INDEX ix_customers_name ON customers(name);
CREATE INDEX ix_customers_phone ON customers(phone) WHERE phone IS NOT NULL;
CREATE INDEX ix_customers_email ON customers(email) WHERE email IS NOT NULL;

DROP VIEW IF EXISTS checkout_reservations;
ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ck_reservations_reservation_status;
ALTER TABLE reservations
  ADD CONSTRAINT ck_reservations_reservation_status
  CHECK (reservation_status IN ('booked', 'checked_in', 'checked_out', 'cancelled'));

ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ck_reservations_payment_status;
ALTER TABLE reservations
  ADD CONSTRAINT ck_reservations_payment_status
  CHECK (payment_status IN ('unpaid', 'paid', 'partially_refunded', 'refunded'));

-- A checked-in stay must continue blocking the room until checkout.
ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ex_reservations_no_booked_overlap;
ALTER TABLE reservations
  ADD CONSTRAINT ex_reservations_no_active_overlap
  EXCLUDE USING gist (
    room_id WITH =,
    daterange(check_in_date, check_out_date, '[)') WITH &&
  )
  WHERE (reservation_status IN ('booked', 'checked_in'));

CREATE OR REPLACE VIEW checkout_reservations AS
SELECT id, reservation_no, room_id, customer_id, check_in_date, check_out_date,
       checked_in_at, checked_out_at, guest_name, guest_kana, guest_gender, guest_age,
       guest_phone, guest_email, guest_count, reservation_form, payment_status,
       reservation_status, total_amount, note, created_at, updated_at
FROM reservations
WHERE reservation_status = 'checked_out';

CREATE TABLE reservation_finances (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id integer NOT NULL UNIQUE REFERENCES reservations(id) ON DELETE CASCADE,
  received_amount numeric(10, 2) NOT NULL DEFAULT 0,
  payment_method varchar(30),
  received_at timestamptz,
  refund_amount numeric(10, 2) NOT NULL DEFAULT 0,
  refunded_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_finance_received_non_negative CHECK (received_amount >= 0),
  CONSTRAINT ck_finance_refund_non_negative CHECK (refund_amount >= 0),
  CONSTRAINT ck_finance_refund_not_over_received CHECK (refund_amount <= received_amount),
  CONSTRAINT ck_finance_payment_method CHECK (
    payment_method IS NULL OR payment_method IN ('cash', 'card', 'transfer', 'platform', 'unknown')
  ),
  CONSTRAINT ck_finance_received_details CHECK (
    (received_amount = 0 AND payment_method IS NULL AND received_at IS NULL)
    OR (received_amount > 0 AND payment_method IS NOT NULL AND received_at IS NOT NULL)
  ),
  CONSTRAINT ck_finance_refund_details CHECK (
    (refund_amount = 0 AND refunded_at IS NULL)
    OR (refund_amount > 0 AND refunded_at IS NOT NULL)
  )
);

-- Preserve the meaning of legacy paid reservations without inventing a payment channel.
INSERT INTO reservation_finances (
  reservation_id, received_amount, payment_method, received_at, refund_amount
)
SELECT
  id,
  CASE WHEN payment_status = 'paid' THEN total_amount ELSE 0 END,
  CASE WHEN payment_status = 'paid' THEN 'unknown' ELSE NULL END,
  CASE WHEN payment_status = 'paid' THEN updated_at ELSE NULL END,
  0
FROM reservations;

CREATE INDEX ix_reservation_finances_received_at ON reservation_finances(received_at);
CREATE INDEX ix_reservation_finances_refunded_at ON reservation_finances(refunded_at);

CREATE TABLE admin_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(64) NOT NULL UNIQUE,
  password_hash varchar(100) NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  failed_attempts integer NOT NULL DEFAULT 0,
  locked_until timestamptz,
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_admin_failed_attempts CHECK (failed_attempts >= 0)
);

CREATE TABLE backup_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  backup_file varchar(1000) NOT NULL,
  status varchar(20) NOT NULL,
  file_size_bytes bigint,
  message varchar(1000),
  started_at timestamptz NOT NULL,
  completed_at timestamptz,
  CONSTRAINT ck_backup_status CHECK (status IN ('started', 'success', 'failed'))
);

CREATE INDEX ix_backup_history_started_at ON backup_history(started_at DESC);
