-- Public multi-room booking requests with a 24-hour inventory hold.

CREATE TABLE public_booking_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_no varchar(18) NOT NULL UNIQUE,
  locale varchar(5) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'pending',
  check_in_date date NOT NULL,
  check_out_date date NOT NULL,
  lead_name varchar(100) NOT NULL,
  lead_email varchar(255) NOT NULL,
  lead_phone varchar(50) NOT NULL,
  country varchar(100) NOT NULL,
  guest_count integer NOT NULL,
  total_amount numeric(12, 2) NOT NULL,
  notes varchar(1000),
  cancel_token_hash char(64) NOT NULL UNIQUE,
  hold_expires_at timestamptz NOT NULL,
  confirmed_at timestamptz,
  rejected_at timestamptz,
  cancelled_at timestamptz,
  rejection_reason varchar(1000),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_public_booking_dates CHECK (check_in_date < check_out_date),
  CONSTRAINT ck_public_booking_locale CHECK (locale IN ('ja', 'zh', 'en')),
  CONSTRAINT ck_public_booking_status CHECK (status IN ('pending', 'confirmed', 'rejected', 'expired', 'cancelled')),
  CONSTRAINT ck_public_booking_guest_count CHECK (guest_count > 0),
  CONSTRAINT ck_public_booking_total CHECK (total_amount >= 0),
  CONSTRAINT ck_public_booking_rejection_reason CHECK (
    status != 'rejected' OR NULLIF(BTRIM(rejection_reason), '') IS NOT NULL
  )
);

CREATE SEQUENCE public_booking_request_no_seq AS bigint MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE INDEX ix_public_booking_status_expiry
  ON public_booking_requests(status, hold_expires_at);
CREATE INDEX ix_public_booking_email_created
  ON public_booking_requests(lead_email, created_at DESC);

ALTER TABLE reservations ADD COLUMN booking_request_id integer
  REFERENCES public_booking_requests(id) ON DELETE RESTRICT;
ALTER TABLE reservations ADD COLUMN guest_category varchar(10);
ALTER TABLE reservation_guests ADD COLUMN guest_category varchar(10);
ALTER TABLE reservations ADD CONSTRAINT ck_reservations_guest_category
  CHECK (guest_category IS NULL OR guest_category IN ('adult', 'child'));
ALTER TABLE reservation_guests ADD CONSTRAINT ck_reservation_guests_category
  CHECK (guest_category IS NULL OR guest_category IN ('adult', 'child'));
CREATE INDEX ix_reservations_booking_request_id ON reservations(booking_request_id, id);

DROP VIEW IF EXISTS checkout_reservations;
ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ck_reservations_reservation_status;
ALTER TABLE reservations
  ADD CONSTRAINT ck_reservations_reservation_status
  CHECK (reservation_status IN ('pending', 'booked', 'checked_in', 'checked_out', 'cancelled'));

ALTER TABLE reservations DROP CONSTRAINT IF EXISTS ex_reservations_no_active_overlap;
ALTER TABLE reservations
  ADD CONSTRAINT ex_reservations_no_active_overlap
  EXCLUDE USING gist (
    room_id WITH =,
    daterange(check_in_date, check_out_date, '[)') WITH &&
  )
  WHERE (reservation_status IN ('pending', 'booked', 'checked_in'));

CREATE OR REPLACE VIEW checkout_reservations AS
SELECT id, reservation_no, room_id, customer_id, booking_request_id, check_in_date, check_out_date,
       checked_in_at, checked_out_at, guest_name, guest_kana, guest_gender, guest_age,
       guest_phone, guest_email, guest_count, reservation_form, payment_status,
       reservation_status, total_amount, note, created_at, updated_at
FROM reservations
WHERE reservation_status = 'checked_out';
