-- Date-scoped room inventory blocks and auditable calendar operations.
-- All business ranges use [start_date, end_date), where end_date is the
-- first date on which the room becomes sellable again.

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE room_inventory_blocks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
  block_type varchar(20) NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason varchar(1000) NOT NULL,
  record_status varchar(20) NOT NULL DEFAULT 'effective',
  split_from_id integer REFERENCES room_inventory_blocks(id) ON DELETE RESTRICT,
  version bigint NOT NULL DEFAULT 0,
  created_by varchar(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_by varchar(64) NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  cancelled_by varchar(64),
  cancelled_at timestamptz,
  cancellation_note varchar(1000),
  CONSTRAINT ck_room_inventory_blocks_type
    CHECK (block_type IN ('stop_sale', 'maintenance')),
  CONSTRAINT ck_room_inventory_blocks_range
    CHECK (start_date < end_date),
  CONSTRAINT ck_room_inventory_blocks_reason
    CHECK (NULLIF(BTRIM(reason), '') IS NOT NULL),
  CONSTRAINT ck_room_inventory_blocks_status
    CHECK (record_status IN ('effective', 'cancelled')),
  CONSTRAINT ck_room_inventory_blocks_cancelled
    CHECK (
      (record_status = 'effective' AND cancelled_at IS NULL AND cancelled_by IS NULL)
      OR
      (record_status = 'cancelled' AND cancelled_at IS NOT NULL AND NULLIF(BTRIM(cancelled_by), '') IS NOT NULL)
    ),
  CONSTRAINT ck_room_inventory_blocks_version CHECK (version >= 0)
);

ALTER TABLE room_inventory_blocks
  ADD CONSTRAINT ex_room_inventory_blocks_no_overlap
  EXCLUDE USING gist (
    room_id WITH =,
    daterange(start_date, end_date, '[)') WITH &&
  )
  WHERE (record_status = 'effective');

CREATE INDEX ix_room_inventory_blocks_calendar
  ON room_inventory_blocks(room_id, start_date, end_date)
  WHERE record_status = 'effective';
CREATE INDEX ix_room_inventory_blocks_split_from
  ON room_inventory_blocks(split_from_id)
  WHERE split_from_id IS NOT NULL;

CREATE TABLE room_inventory_block_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id varchar(36) NOT NULL,
  block_id integer NOT NULL REFERENCES room_inventory_blocks(id) ON DELETE RESTRICT,
  room_id integer NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
  event_type varchar(30) NOT NULL,
  before_type varchar(20),
  before_start_date date,
  before_end_date date,
  before_reason varchar(1000),
  before_status varchar(20),
  after_type varchar(20),
  after_start_date date,
  after_end_date date,
  after_reason varchar(1000),
  after_status varchar(20),
  action_note varchar(1000),
  actor_username varchar(64) NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_room_inventory_block_events_type CHECK (
    event_type IN ('created', 'updated', 'released', 'partially_released', 'split_created')
  )
);

CREATE INDEX ix_room_inventory_block_events_block_time
  ON room_inventory_block_events(block_id, occurred_at DESC, id DESC);
CREATE INDEX ix_room_inventory_block_events_operation
  ON room_inventory_block_events(operation_id, id);

ALTER TABLE reservations ADD COLUMN cancellation_reason varchar(1000);
ALTER TABLE reservations ADD COLUMN cancelled_by varchar(64);
ALTER TABLE reservations ADD COLUMN cancelled_at timestamptz;

UPDATE reservations
SET cancellation_reason = COALESCE(NULLIF(BTRIM(note), ''), '移行前のキャンセル（理由未記録）'),
    cancelled_by = 'migration',
    cancelled_at = COALESCE(updated_at, now())
WHERE reservation_status = 'cancelled'
  AND NULLIF(BTRIM(cancellation_reason), '') IS NULL;

-- A room row is the serialization point shared by reservation and inventory
-- writers. These triggers keep direct SQL and future writers from bypassing
-- the cross-table rule that cannot be expressed as one exclusion constraint.
CREATE OR REPLACE FUNCTION enforce_reservation_not_inventory_blocked()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.reservation_status IN ('pending', 'booked', 'checked_in') THEN
    PERFORM id FROM rooms WHERE id = NEW.room_id FOR UPDATE;
    IF EXISTS (
      SELECT 1
      FROM room_inventory_blocks b
      WHERE b.room_id = NEW.room_id
        AND b.record_status = 'effective'
        AND b.start_date < NEW.check_out_date
        AND b.end_date > NEW.check_in_date
    ) THEN
      RAISE EXCEPTION 'reservation overlaps a room inventory block'
        USING ERRCODE = '23P01';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_reservations_inventory_block_guard ON reservations;
CREATE TRIGGER trg_reservations_inventory_block_guard
BEFORE INSERT OR UPDATE OF room_id, check_in_date, check_out_date, reservation_status
ON reservations
FOR EACH ROW
EXECUTE FUNCTION enforce_reservation_not_inventory_blocked();

CREATE OR REPLACE FUNCTION enforce_inventory_block_not_reserved()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.record_status = 'effective' THEN
    PERFORM id FROM rooms WHERE id = NEW.room_id FOR UPDATE;
    IF EXISTS (
      SELECT 1
      FROM reservations r
      WHERE r.room_id = NEW.room_id
        AND r.reservation_status IN ('pending', 'booked', 'checked_in')
        AND r.check_in_date < NEW.end_date
        AND r.check_out_date > NEW.start_date
    ) THEN
      RAISE EXCEPTION 'room inventory block overlaps an active reservation'
        USING ERRCODE = '23P01';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_room_inventory_blocks_reservation_guard ON room_inventory_blocks;
CREATE TRIGGER trg_room_inventory_blocks_reservation_guard
BEFORE INSERT OR UPDATE OF room_id, start_date, end_date, record_status
ON room_inventory_blocks
FOR EACH ROW
EXECUTE FUNCTION enforce_inventory_block_not_reserved();
